openapi: "3.0.0"
info:
  title: OAuth2 API Server
  description: OAuth2 API Server, other docs available at user-cred and implicit
  version: "0.0.1"
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    tokenAuth:
      type: http
      scheme: bearer
paths:
  /authorize:
    get:
      summary: Authorization code request
      description: Issues an authorization code to valid clients
      tags:
        - Authorization Code Grant Type
      parameters:
        - name: client_id
          in: query
          description: A registered client id
          required: true
          schema:
            type: string
          example: "c2ce91a6-98b6-4d4b-99ad-eeb174c0b6d5"
        - name: response_type
          in: query
          description: Request for the authorization code flow
          required: true
          schema:
            type: string
          example: "code"
        - name: redirect_url
          in: query
          description: A redirect url to redirect the client. Redirect url's should be registered with the server
          schema:
            type: string
        - name: redirect
          in: query
          description: Indicate to the server whether a redirect, status code 302, is required
          schema:
            type: string
          example: "false"
        - name: state
          in: query
          description: A client generated random token to prevent CSRF
          schema:
            type: string
      responses:
        '200':
          description: Ok
          headers:
            Location:
              description: Redirect url the client will be sent to complete the authorization process
              schema:
                type: string
          content:
            application/json:
              description: Content is present because the redirect param has been set as false
              schema:
                required:
                  - location
                properties:
                  location:
                    type: string
        '302':
          description: Found
          headers:
            Location:
              description: Redirect url
              schema:
                type: string
          content:
            application/json:
              description: Redirected to the specified redirect url
              schema:
                required:
                  - location
                properties:
                  location:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
        default:
          description: The client is redirected
          headers:
            Location:
              description: Redirect url
              schema:
                type: string
  /token:
    get:
      summary: Authorization code, token request
      description: >-
        Issues an access tokens to valid authorization codes.
        An example bearer token: c2ce91a6-98b6-4d4b-99ad-eeb174c0b6d5:c2VjcmV0
      tags:
        - Authorization Code Grant Type
      security:
        - bearerAuth: []
      parameters:
        - name: grant_type
          in: query
          description: The grant type token required
          required: true
          schema:
            type: string
          example: "authorization_code"
        - name: code
          in: query
          required: true
          description: A valid authorization code
          schema:
            type: string
          example: "512b9672-0a8a-11e9-9fbb-425720917a6d"
        - name: refresh
          in: query
          required: false
          description: Specify if a refresh token is required, default is false
          schema:
            type: string
          example: "true"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Token'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
    put:
      summary: Issue a new token
      description: Issue a new token, using a refresh token
      tags:
        - Authorization Code Grant Type
      parameters:
        - name: refresh_token
          in: query
          description: Refresh token to be used to issue a new token
          required: true
          schema:
            type: string
        - name: refresh
          in: query
          required: false
          description: Specify if a refresh token is required
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Inspection'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
    delete:
      summary: Revoke tokens
      description: Revoke issued tokens
      tags:
        - Authorization Code Grant Type
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: query
          description: Token we want to revoke
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Inspection'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
  /check:
     get:
      summary: Inspect tokens
      description: Inspects a token details
      tags:
        - Authorization Code Grant Type
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: query
          description: Token which we want to inspect
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Inspection'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
definitions:
  Token:
    properties:
      access_token:
         type: string
      expires_in:
        type: integer
        format: int64
      scope:
        type: string
      refresh_token:
        type: string
  Inspection:
    properties:
      active:
        type: boolean
      expires_in:
        type: integer
        format: int64
      grant_type:
        type: string
      scope:
        type: array
        items:
          type: string
      token_type:
        type: string
      client_id:
        type: string
      user_uid:
        type: string
  Error:
    properties:
      title:
        type: string
      description:
        type: array
        items:
          type: string
      link:
        type: string