openapi: "3.0.0"
info:
  title: OAuth2 API Server
  description: OAuth2 API Server, other docs are available at auth-code and user-cred
  version: "0.0.1"
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    tokenAuth:
      type: http
      scheme: bearer
paths:
  /token:
    get:
      summary: Implicit token request
      description: Issues an access token to a registered client.
      tags:
        - Implicit Grant Type
      parameters:
        - name: grant_type
          in: query
          description: The grant type token required
          required: true
          schema:
            type: string
          example: "implicit"
        - name: client_id
          in: query
          required: true
          description: A valid client id
          schema:
            type: string
          example: "c2ce91a6-98b6-4d4b-99ad-eeb174c0b6d5"
        - name: redirect_url
          in: query
          description: A redirect url to redirect the client. Redirect url's should be registered with the server
          schema:
            type: string
        - name: refresh
          in: query
          required: false
          description: Specify if a refresh token is required, default is false
          schema:
            type: string
          example: "true"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Token'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
    put:
      summary: Issue a new token
      description: Issue a new token, using a refresh token
      tags:
        - Implicit Grant Type
      parameters:
        - name: refresh_token
          in: query
          description: Refresh token to be used to issue a new token
          required: true
          schema:
            type: string
        - name: refresh
          in: query
          required: false
          description: Specify if a refresh token is required
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Inspection'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
    delete:
      summary: Revoke tokens
      description: Revoke issued tokens
      tags:
        - Implicit Grant Type
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: query
          description: Token we want to revoke
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Inspection'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
  /check:
     get:
      summary: Inspect tokens
      description: Inspects a token details
      tags:
        - Implicit Grant Type
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: query
          description: Token which we want to inspect
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/definitions/Inspection'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Error'
definitions:
  Token:
    properties:
      access_token:
         type: string
      expires_in:
        type: integer
        format: int64
      scope:
        type: string
      refresh_token:
        type: string
  Inspection:
    properties:
      active:
        type: boolean
      expires_in:
        type: integer
        format: int64
      grant_type:
        type: string
      scope:
        type: array
        items:
          type: string
      token_type:
        type: string
      client_id:
        type: string
      user_uid:
        type: string
  Error:
    properties:
      title:
        type: string
      description:
        type: array
        items:
          type: string
      link:
        type: string