version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
  api-docs:
    image: swaggerapi/swagger-ui
    links:
      - api
    environment:
      - API_URL=http://localhost:3000/?docs=auth-code
    ports:
      - "8080:8080"
