swagger: "2.0"
info:
  title: OAuth2 API Server
  description: OAuth 2 API Server
  version: "1.0.0"
host: "localhost:3000"
basePath: "/"
schemes:
  - http
consumes:
  - application/json
paths:
  /authorize:
    get:
      summary: Authorization Code Grant Type
      description: Issues an authorization code to valid clients
      parameters:
        - name: client_id
          in: query
          description: Client id of a registered user or client e.g an api
          required: true
          type: string
        - name: request_type
          in: query
          description: Grant type requested, the only available option is <code>code</code>
          required: true
          type: string
        - name: redirect_url
          in: query
          description: A redirect url to redirect the client. A Redirect url should be registered with the server
          type: string
        - name: redirect
          in: query
          description: A boolean param to indicate to the server whether a redirect, status code 302, is required
          type: string
          default: true
        - name: state
          in: query
          description: A client random generated token to prevent CSRF
          type: string
      security:
          - apikey: []
      tags:
          - Authorize
      responses:
        "302":
          description: Found
        "404":
          description: Not Found
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      title:
        type: string
      message:
        type: string
      links:
        type: string