swagger: "2.0"
info:
  title: OAuth2 API Server
  description: OAuth 2 API Server
  version: "1.0.0"
host: "localhost:3000"
basePath: "/"
schemes:
  - http
consumes:
  - application/json
paths:
  /authorize:
    get:
      summary: Authorization Code Grant Type
      description: Issues an authorization code to valid clients
      parameters:
        - name: client_id
          in: query
          description: A registered client id
          required: true
          type: string
        - name: response_type
          in: query
          description: Request for the authorization code flow
          required: true
          type: string
        - name: redirect_url
          in: query
          description: A redirect url to redirect the client. A Redirect url should be registered with the server
          type: string
        - name: redirect
          in: query
          description: Indicate to the server whether a redirect, status code 302, is required.
          type: string
          value: false
        - name: state
          in: query
          description: A client generated random token to prevent CSRF
          type: string
      security:
          - apikey: []
      tags:
          - Authorize
      responses:
        "302":
          description: Found
        "404":
          description: Not Found
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      title:
        type: string
      description:
        type: array
        items:
          type: string
      link:
        type: string